### ISSUE TITLE
i18n - locales not working

### ISSUE THREAD

**Issue by rinti** [stefanpenner/ember-moment#110]
Hi. I'm having the same issue as #105 

However I'm quite certain I'm not loading two instances of moment. (I've grepped for moment in my files and nothing seems out of the ordinary)

And i've tried both {{moment-from-now date locale='sv'}} and setting the locale in the application route.
I've also tried `import moment from 'moment'` and doing `moment.locale('sv')`.
Also tried `this.set('moment.locale', 'sv')`
I've also downloaded ember-moment and ran the tests which does pass.
The Swedish locale is showing up in vendor.js.

I'm not really sure what more I can try. Any suggestions?

**Comment by jasonmit** [comment]
What version of moment is being bundled?  You also said when you pulled down the repo and ember test ci that tests are failing?

**Comment by rinti** [comment]
The tests are passing in the repo i pulled home.

I just realized it is a conflict with another app which includes moment:
https://github.com/edgycircle/ember-pikaday

Is there any way to get around this?

**Comment by jasonmit** [comment]
If they both depend on >= 2.8.0 than there shouldn't be an issue.  What version of moment is the conflict resolving to?  It shouldn't be an issue if you just override the version in bower.json.

**Comment by jasonmit** [comment]
Also, I'm not really sure how this will work since it all depends on the order in which the locales are appended to your vendor.js. 

https://github.com/jasonmit/ember-cli-moment-shim/blob/master/index.js#L43-L47

Pikaday doesn't seem to take into account locales and there for does not care about ordering:
https://github.com/edgycircle/ember-pikaday/blob/master/index.js#L10

I'm not sure what to say other than these two addons do not work together out of the box.  As it's a dependency issue.  You can maybe send a PR to pikaday to use the ember-cli-moment-shim,

Remove:
https://github.com/edgycircle/ember-pikaday/blob/master/index.js#L10

Replace:
https://github.com/edgycircle/ember-pikaday/blob/master/blueprints/ember-pikaday/index.js#L8
with
https://github.com/stefanpenner/ember-moment/blob/master/blueprints/ember-moment/index.js#L10-L12

**Comment by rinti** [comment]
Thanks Jason. Will do that.

**Comment by jasonmit** [comment]
I'm not sure if this is an option, but I also maintain another library which handles time/date/relative time along with localization: https://github.com/yahoo/ember-intl/wiki/Format-Date-&-Time-Options
