### ISSUE TITLE
Call static methods on momentjs in the correct locale.

### ISSUE THREAD

**Issue by cibernox** [stefanpenner/ember-moment#196]
The moment service allows the user to set a locale for the app, but it doesn't change the global moment locale. Instead, it sets a locale in the service and the the `service.moment()` method applies the locale and timezone every time it's called.

Is this behaviour (not changing the global locale) intended? Why?

Assuming it is, now to the real question. MomentJS has a few "static" methods that are locale-dependent. By example, for getting the name of the days of the week you can do `moment.weekdays()`. Note that this methods cannot be called on a moment instance, they are methods on the global.

I need those methods to be locale-dependent, so I resorted to this helper function:

```js
function withLocale(locale, fn) {
  let returnValue;
  if (locale) {
    let previousLocale = moment.locale();
    moment.locale(locale);
    returnValue = fn();
    moment.locale(previousLocale);
  } else {
    returnValue = fn();
  }
  return returnValue;
}
```

Then, when I want to call a static method in, I do:

```js
withLocale('fr', () => moment.weekdaysShort());
```

Would to consider such static method to be on the moment service so it uses the set locale automatically?

Example:

```js
momentService.localize((moment) => moment.weekdays());
```
The implementation would be something like:
```js
localize(fn) {
  let returnValue;
  let locale = this.get('locale');
  if (locale) {
    let previousLocale = moment.locale();
    moment.locale(locale);
    returnValue = fn(moment);
    moment.locale(previousLocale);
  } else {
    returnValue = fn(moment);
  }
  return returnValue;
}
```

Sounds good?

**Comment by jasonmit** [comment]
> Is this behaviour (not changing the global locale) intended? Why?

The scope of the locale stays scoped to the app instance versus being an app global.  I feel this has some benefits for testing, instances where someone might have multiple Ember apps running, etc. 

That said, I'm still opened to consider setting the global and/or your recommendation for a localize service utility method..

**Comment by mfeltz** [comment]
> Assuming it is, now to the real question. MomentJS has a few "static" methods that are locale-dependent. By example, for getting the name of the days of the week you can do moment.weekdays(). Note that this methods cannot be called on a moment instance, they are methods on the global.

@cibernox - With regard to the weekdays() method, this might help, I was able to grab the weekdays in the correct locale without as much of a work around doing this: `momentService.moment().localeData().weekdaysShort()[index]`

@jasonmit - I'm using the moment service in my application and where I'm running into the issue of not having the global locale changed is with the helpers because those reference the global instance of moment. I see where you'd want to keep the locale scoped to the service because of testing, however, anywhere the helpers are used it is using a different reference. It may be helpful to convert the helpers to using the service instead of global moment.

**Comment by jasonmit** [comment]
7.3.0 resolves this
