### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by herzzanu** [stefanpenner/ember-moment#227]
`this.get('moment').setTimeZone('America/Los_Angeles')` should be 
`this.get('moment').set('timezone', 'America/Los_Angeles')` 

and 
`this.get('moment').setLocale('es')` should be 
`this.get('moment').set('locale', 'es')`

At least that's how it works for me.

**Comment by jasonmit** [comment]
Yes you can go around the moment service but it is the public API for a reason.  Moment does not trigger events on locale change, and I have no intentions of monkey patching moment to observe locale changes.  This is required so people go through these setter methods in order to trigger things like helper recomputes when the locale changes at runtime.
